### ISSUE TITLE
Decide about cythonizing

### ISSUE THREAD

**Issue by ceball** [ioam/param#166]
Currently, pip install/python setup.py attempts to cythonize. This may bring performance improvements (e.g. when creating many parameterized objects), although we have no performance tests running to back that up (https://github.com/ioam/param/issues/165). However, there are a number of potential downsides of cythonizing:

(1) source code is obscured/people might think it's not purely python e.g. if they try to open the file they've imported;

(2) possible errors/incompatibilities introduced by cython we're not aware of (although you could also argue cythonizing helps catch a class of problems, and also cythonizing by default means we're all testing cython's effects all the time);

(3) possible installation failures (e.g. https://github.com/ioam/param/issues/129) or confusion (e.g. https://github.com/ioam/param/issues/161);

(4) just more stuff to think about overall.

Incidentally, conda packages have never included cythonized param. People would only have the cythonized version by pip install/python setup.py from pypi/github on a machine with cython and a working compiler.

**Comment by ceball** [comment]
pip-installed (i.e. cythonized) param causes the following error somewhere in topographica's tests:

```
$ TOPO_SKIP_RUNTESTS_GUI_IF_NO_DISPLAY=1 DISPLAY= ./topographica -t all
[...]
Traceback (most recent call last):
  File "/Users/cball/code/ioam/topographica/topo/command/__init__.py", line 867, in __call__
    save_script_repr()
  File "/Users/cball/code/ioam/topographica/topo/command/__init__.py", line 396, in save_script_repr
    script = header+topo.sim.script_repr()
  File "/Users/cball/code/ioam/topographica/topo/base/simulation.py", line 1537, in script_repr
    sorted(self.objects().values(), cmp=lambda x, y: cmp(x.name,y.name))]
  File "/Users/cball/code/ioam/topographica/topo/base/simulation.py", line 240, in script_repr
    super(EventProcessor,self).script_repr(imports=imports,prefix=prefix)
  File "param/parameterized.py", line 1236, in param.parameterized.Parameterized.script_repr
    return self.pprint(imports,prefix, unknown_value=None, qualify=True,
  File "param/parameterized.py", line 1285, in param.parameterized.Parameterized.pprint
    value = pprint(values[k], imports, prefix=prefix,settings=[],
  File "param/parameterized.py", line 891, in param.parameterized.pprint
    rep=val.script_repr(imports, prefix+"    ")
  File "param/parameterized.py", line 1236, in param.parameterized.Parameterized.script_repr
    return self.pprint(imports,prefix, unknown_value=None, qualify=True,
  File "param/parameterized.py", line 1285, in param.parameterized.Parameterized.pprint
    value = pprint(values[k], imports, prefix=prefix,settings=[],
  File "param/parameterized.py", line 887, in param.parameterized.pprint
    rep = script_repr_reg[type(val)](val,imports,prefix,settings)
  File "param/parameterized.py", line 912, in param.parameterized.container_script_repr
    result.append(pprint(i,imports,prefix,settings))
  File "param/parameterized.py", line 891, in param.parameterized.pprint
    rep=val.script_repr(imports, prefix+"    ")
  File "param/parameterized.py", line 1236, in param.parameterized.Parameterized.script_repr
    return self.pprint(imports,prefix, unknown_value=None, qualify=True,
  File "param/parameterized.py", line 1285, in param.parameterized.Parameterized.pprint
    value = pprint(values[k], imports, prefix=prefix,settings=[],
  File "param/parameterized.py", line 891, in param.parameterized.pprint
    rep=val.script_repr(imports, prefix+"    ")
  File "param/parameterized.py", line 1236, in param.parameterized.Parameterized.script_repr
    return self.pprint(imports,prefix, unknown_value=None, qualify=True,
  File "param/parameterized.py", line 1261, in param.parameterized.Parameterized.pprint
    spec = inspect.getargspec(self.__init__)
  File "/Users/cball/Eunectes/mc3/envs/topographica/lib/python2.7/inspect.py", line 815, in getargspec
    raise TypeError('{!r} is not a Python function'.format(func))
TypeError: <cyfunction Time.__init__ at 0x113cd0c50> is not a Python function
[...]
runtests: targets with errors: 2 [scriptrepr,batch]
runtests: ran 7 targets [training,unopt,snapshots,pickle,scriptrepr,batch,maps]
WARNING:root:Time: 000000.00 CommandLine: Errors encountered; exiting with return code 2
```

Need to investigate.

**Comment by ceball** [comment]
Note: the above probably goes away with python>= 3.4 (http://bugs.python.org/issue17159)
