### ISSUE TITLE
Broken error message when creating a List with a bad default value

### ISSUE THREAD

**Issue by ceball** [ioam/param#75]
```
>>> import param
>>> class A(param.Parameterized):
...     a = param.List(default=None)
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in A
  File "param\__init__.py", line 1073, in __init__
    self._check_bounds(default)
  File "param\__init__.py", line 1091, in _check_bounds
    raise ValueError("List '%s' must be a list."%(self._attrib_name))
AttributeError: _attrib_name
```

`_attrib_name` hasn't been set yet because `__init__` calls `_check_bounds` before calling Parameter's `__init__`.

When fixing, would be worthwhile checking for this kind of error elsewhere too. (For a bigger task, there's probably a good chance of simplifying `_attrib_name`-related code...)

**Comment by ceball** [comment]
This has been fixed. Now you at least get the right kind of error message:

```python
>>> class A(param.Parameterized):
...     a = param.List(default=1)
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in A
  File "param/__init__.py", line 1065, in __init__
    self._check_bounds(default)
  File "param/__init__.py", line 1084, in _check_bounds
    raise ValueError("List '%s' must be a list."%(self._attrib_name))
ValueError: List 'None' must be a list.
```
